//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カートに入れる.
        /// </summary>
        public static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示順番.
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メータタイトル.
        /// </summary>
        public static string Category_Metatitle {
            get {
                return ResourceManager.GetString("Category_Metatitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Danh Mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Cha.
        /// </summary>
        public static string Category_ParentID {
            get {
                return ResourceManager.GetString("Category_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu Đề Seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連絡　:.
        /// </summary>
        public static string ContactUS {
            get {
                return ResourceManager.GetString("ContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 買い物続けます.
        /// </summary>
        public static string ContBuy {
            get {
                return ResourceManager.GetString("ContBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部削除.
        /// </summary>
        public static string DeleteCart {
            get {
                return ResourceManager.GetString("DeleteCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英語.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリー.
        /// </summary>
        public static string lblListCategory {
            get {
                return ResourceManager.GetString("lblListCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい商品.
        /// </summary>
        public static string lblNewPro {
            get {
                return ResourceManager.GetString("lblNewPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベストセラー.
        /// </summary>
        public static string lblNo1 {
            get {
                return ResourceManager.GetString("lblNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て見る.
        /// </summary>
        public static string lblSeeAll {
            get {
                return ResourceManager.GetString("lblSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーリスト.
        /// </summary>
        public static string ListUserLable {
            get {
                return ResourceManager.GetString("ListUserLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm nào trong giỏ hàng.
        /// </summary>
        public static string NullCart {
            get {
                return ResourceManager.GetString("NullCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジに進む.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値段.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写真.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名.
        /// </summary>
        public static string ProName {
            get {
                return ResourceManager.GetString("ProName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Quanlity {
            get {
                return ResourceManager.GetString("Quanlity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バンバン・ショッピングカート.
        /// </summary>
        public static string ShopCartTitle {
            get {
                return ResourceManager.GetString("ShopCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ショッピングカート.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 価格.
        /// </summary>
        public static string ToMoney {
            get {
                return ResourceManager.GetString("ToMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード更新.
        /// </summary>
        public static string UpDaCart {
            get {
                return ResourceManager.GetString("UpDaCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バンバンショッピングようこそ.
        /// </summary>
        public static string WellcomeString {
            get {
                return ResourceManager.GetString("WellcomeString", resourceCulture);
            }
        }
    }
}
